"""Run setup_and_run.py and publish its output as a static report in site/index.html.

    python build_site.py
"""
import html
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "site" / "index.html"
RULE = "=" * 70

CSS = """
:root{--bg:#ffffff;--fg:#1f2328;--muted:#656d76;--card:#f6f8fa;--border:#d0d7de;--accent:#0969da}
@media (prefers-color-scheme:dark){:root{--bg:#0d1117;--fg:#e6edf3;--muted:#8d96a0;--card:#161b22;--border:#30363d;--accent:#4493f8}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
main{max-width:1040px;margin:0 auto;padding:40px 16px 80px}
header p{color:var(--muted);margin:4px 0 0}
nav{display:flex;flex-wrap:wrap;gap:8px;margin:24px 0 8px}
nav a{color:var(--accent);text-decoration:none;border:1px solid var(--border);border-radius:999px;padding:4px 12px;font-size:14px}
h1{font-size:28px;margin:0}
h2{font-size:20px;margin:48px 0 8px;padding-bottom:6px;border-bottom:1px solid var(--border)}
h3{font-size:15px;margin:24px 0 8px;color:var(--muted);font-weight:600}
pre{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:12px 14px;overflow-x:auto;
    font:13px/1.45 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;margin:0}
details{margin-top:48px}
summary{cursor:pointer;font-weight:600;font-size:18px}
"""


def run_script():
    result = subprocess.run([sys.executable, str(ROOT / "setup_and_run.py")],
                            capture_output=True, text=True, cwd=ROOT, check=True)
    return result.stdout


def split_header(output):
    """The banner is RULE / title / author line / RULE; return (title, author, rest)."""
    lines = output.splitlines()
    if len(lines) > 3 and lines[0] == RULE and lines[3] == RULE:
        return lines[1].strip(), lines[2].strip(), "\n".join(lines[4:])
    return "HI 671 Query 2", "", output


def parse(output):
    """Split the console output into [(part_title, [(step_title, block), ...]), ...]."""
    parts, title, steps, step, buf = [], None, [], None, []

    def flush_step():
        nonlocal step, buf
        text = "\n".join(buf).strip("\n")
        if step or text:
            steps.append((step, text))
        step, buf = None, []

    lines = output.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line == RULE and i + 2 < len(lines) and lines[i + 2] == RULE:
            flush_step()
            if title is not None or steps:
                parts.append((title, steps))
            title, steps = lines[i + 1].strip(), []
            i += 3
            continue
        m = re.match(r"^--- (.+?) ---$", line)
        if m:
            flush_step()
            step = m.group(1)
        else:
            buf.append(line)
        i += 1
    flush_step()
    parts.append((title, steps))
    return [(t, [s for s in st if s[0] or s[1]]) for t, st in parts if t or st]


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def render(title_text, author, body_parts, sql):
    nav = "".join(f'<a href="#{slug(t)}">{html.escape(t.split(":")[0].title())}</a>'
                  for t, _ in body_parts if t)
    sections = []
    for title, steps in body_parts:
        sections.append(f'<h2 id="{slug(title)}">{html.escape(title)}</h2>')
        for step, block in steps:
            if step:
                sections.append(f"<h3>{html.escape(step)}</h3>")
            if block.strip():
                sections.append(f"<pre>{html.escape(block)}</pre>")
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>HI 671 Query 2 Results</title>
<style>{CSS}</style></head>
<body><main>
<header><h1>{html.escape(title_text.title().replace("Hi 671", "HI 671"))}</h1><p>{html.escape(author)}</p>
<p>Generated by running <code>setup_and_run.py</code> on synthetic data in DuckDB.</p></header>
<nav>{nav}</nav>
{"".join(sections)}
<details><summary>SQL (HI671_Query2.sql)</summary><pre>{html.escape(sql)}</pre></details>
</main></body></html>
"""


def main():
    title_text, author, rest = split_header(run_script())
    parts = parse(rest)
    sql = (ROOT / "HI671_Query2.sql").read_text()
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(render(title_text, author, parts, sql))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(parts)} parts, {sum(len(s) for _, s in parts)} steps)")


if __name__ == "__main__":
    main()
